services:
  rails:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/ecomm-ror
    working_dir: /ecomm-ror
    depends_on:
      - db


  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123456
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  pgdata:
