default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: sa123456
  host: db # Este es el nombre del servicio en docker-compose.yml


development:
  <<: *default
  database: preconsigna_development


test:
  <<: *default
  database: preconsigna_test


production:
  <<: *default
  database: preconsigna_production
  username: preconsigna
  password: sa123456